language: csharp
mono: none
dotnet: 2.1.302

install:
  - dotnet restore Poetracker.sln
  - sh -c "cd Web && npm install"

script:
  - sh -c "cd Web && npm start"
  - dotnet test ./Web.Tests/Web.Tests.csproj
  - dotnet publish ./Poetracker.sln